version: '3.8'
services:

  isen_controller-prod:
    image: openjdk:17
    container_name: tanhua-server-prod
    hostname: tanhua-server-prod
    privileged: true
    network_mode: host
    volumes:
      - ../o9o-controller:/tmp/o9o-controller:rw
      - ../hello.txt:/tmp/hello.txt:rw
    #      - /etc/timezone:/etc/timezone
    #      - /etc/localtime:/etc/localtime
    restart: always
    user: 0:0
    working_dir: /tmp/o9o-controller/target/
    command: /bin/bash -c "java -jar o9o-controller-1.0.0-exec.jar"
    #    command: /bin/bash -c "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5004 -jar o9o-controller-1.0.0-exec.jar"
    healthcheck:
      test: "curl --silent --fail localhost:8081/getstate || exit 1"
      interval: 30s
      timeout: 3s
      retries: 1
    environment:
      TZ: Asia/Shanghai
    #      - SET_CONTAINER_TIMEZONE=true
    #      - CONTAINER_TIMEZONE=Asia/Shanghai
#    depends_on:
#      - "mysql"

#  mysql:
#    image: mysql:5.7
#    container_name: o9o-server-mysql
#    hostname: o9o-server-mysql
#    restart: always
#    environment:
#      TZ: Asia/Shanghai
#      MYSQL_DATABASE: 'emby'
#      MYSQL_USER: 'ocd'
#      MYSQL_PASSWORD: '376HEdUj1y4ZJn5'
#      MYSQL_ROOT_PASSWORD: '376HEdUj1y4ZJn5'
#    ports:
#      - '3306:3306'
#    volumes:
#      - ./my-db:/var/lib/mysql
#    healthcheck:
#      test: [ "CMD-SHELL","mysql -u ocd -p376HEdUj1y4ZJn5" ]
#      interval: 10s
#      timeout: 1s
#      retries: 3
#      start_period: 30s

  redis:
    image: redis:latest
    hostname: o9o-redis
    container_name: o9o-redis
    restart: always
    privileged: true
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
#    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    command:
      --requirepass "376HEdUj1y4ZJn5"
    ports:
      - 6379:6379
    environment:
      - TZ="Asia/Shanghai"