logging:
  level:
    root: info

# spring配置
spring:
  mail:
    # 邮件 smtp 配置, 异常上报
    host: smtp.mail.me.com
    port: 587
    username: i@@icloud.com
    default-encoding: utf-8
    password: fadfdasdsgdf
    from: i@ocd0522.tk
  # 自动配置 引入Druid
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 数据置情况
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化时建立物理连接的个数
      initial-size: 3
      # 连接池最小连接数
      min-idle: 3
      # 连接池最大连接数
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-connect-error-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      # 用来检测连接是否有效的sql 必须是一个查询语句
      # mysql中为 select 'x'
      # oracle中为 select 1 from dual
      validation-query: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: false
      # 配置扩展插件
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 定时输出统计信息到日志中，并每次输出日志会导致清零（reset）连接池相关的计数器。
      time-between-log-stats-millis: 300000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      # 配置DruidStatViewServlet
      stat-view-servlet:
        # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        url-pattern: '/druid/*'
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 0.0.0.0/0
        # IP黑名单 (存在共同时，deny优先于allow)
        #        deny: 192.168.0.128
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: xxxxxx
    dynamic:
      # 默认数据源（主数据源）
      primary: mysql
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      # 配置数据源
      datasource:
        # 主数据源
        mysql:
          url: jdbc:mysql://172.17.0.1:3307/tanhua?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
          username: root
          password: xxxxxx
          driverClassName: com.mysql.cj.jdbc.Driver

        # 魔改的 jellyfin mysql 数据源
        jellyfin:
          url: jdbc:mysql://172.17.0.1:3307/jellyfin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
          username: root
          password: xxxxxx
          driverClassName: com.mysql.cj.jdbc.Driver

  # Redis配置
  redis:
    host: 172.17.0.1
    port: 6379
    password: xxxxxx
    jedis:
      pool:
        # 连接池最大连接数 (使用负值表示没有限制)
        max-active: 50
        # 连接池最大阻塞等待时间 (使用负值表示没有限制)
        max-wait: 3000ms
        # 连接池中的最大空闲连接数
        max-idle: 20
        # 连接池中的最小空闲连接数
        min-idle: 5
    # 连接超时时间 (毫秒)
    timeout: 5000ms

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ocd:
  crash: "tanhua-正式"

emby:
  url:  http://127.0.0.1:8080/
  apikey: xxxxxx

emby-jump: web/index.html#!/item?id=%s&serverId=%s

bot:
  group_nick: xxxxxx
  token: xxxxxx
  name: xxxxxx
  groupId: xxxxxx
  channel: xxxxxx
  groupName: xxxxxx
  unblockPoints: 150
  expDay: 30
  isDelete: true
  notify_channel: xxxxxx
  wikiName: 暂无 wiki
  wikiUrl: https://ocdlive.com